add conclusion docs
AICoE/elyra-aidevsecops-tutorial pull request #247
Opened 2021-08-17 15:17 UTC by isabelizimm

## Related Issues and Dependencies

closes #241 

## This introduces a breaking change

- [ ] Yes
- [X] No

## Description

add conclusion/congratulations page

2021-08-17 15:17 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **michaelclifford** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @michaelclifford` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Felyra-aidevsecops-tutorial).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["michaelclifford"]} -->

2021-08-17 18:29 UTC, oindrillac reviewed
/lgtm 👍

2021-08-17 19:18 UTC, MichaelClifford requested changes

2021-08-17 19:18 UTC, MichaelClifford commented on docs/source/conclusion.md
> +You started with **[Meteor](http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud)** hosted by **[Operate First](https://operate-first.cloud)**. Next, you used **[JupyterHub](https://jupyter.org
```suggestion
You started with either **[ Project Meteor](http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud)** or **[Operate First](https://operate-first.cloud)** to deploy your own **[JupyterHub](https://jupyter.org/hub)** instance, launch notebook images with Jupyter tooling and leverage **[Project Thoth](https://thoth-station.ninja/)** bots to intelligently manage your dependencies. With your notebooks running, **[Elyra](https://github.com/elyra-ai/elyra)** JupyterLab extensions supported your AI projects with add-ons such as **[Kubeflow Pipelines](https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/)** for end-to-end experiments. Finally, you deployed and monitored your model using Flask.
```

2021-08-17 19:29 UTC, chauhankaranraj requested changes

2021-08-17 19:29 UTC, chauhankaranraj commented on docs/source/conclusion.md
> +You started with **[Meteor](http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud)** hosted by **[Operate First](https://operate-first.cloud)**. Next, you used **[JupyterHub](https://jupyter.org
```suggestion
You started with **[Meteor](http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud)** hosted by **[Operate First](https://operate-first.cloud)**. Next, you used **[JupyterHub](https://jupyter.org/hub)** to launch notebook images with Jupyter tooling and leveraged **[Project Thoth](https://thoth-station.ninja/)** bots to intelligently manage your dependencies. With your notebooks running, **[Elyra](https://github.com/elyra-ai/elyra)** JupyterLab extensions supported your AI projects with add-ons such as **[Kubeflow Pipelines](https://www.kubeflow.org/docs/pipelines/overview/pipelines-overview/)** for end to end experiments. Finally, you deployed your model as a Flask application, and set up monitoring using Prometheus and Grafana.
```

2021-08-18 15:05 UTC, chauhankaranraj approved these changes
/lgtm :rocket:

2021-08-18 15:05 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/247#pullrequestreview-732996988" title="LGTM">chauhankaranraj</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **michaelclifford** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @michaelclifford` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Felyra-aidevsecops-tutorial).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["michaelclifford"]} -->

2021-08-18 18:10 UTC, MichaelClifford commented
/approve

2021-08-18 18:10 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/247#pullrequestreview-732996988" title="LGTM">chauhankaranraj</a>*, *<a href="https://github.com/AICoE/elyra-aidevsecops-tutorial/pull/247#issuecomment-901323765" title="Approved">MichaelClifford</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=AICoE%2Felyra-aidevsecops-tutorial).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/AICoE/elyra-aidevsecops-tutorial/blob/master/OWNERS)~~ [MichaelClifford]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-08-18 18:17 UTC, merged